[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
